### create array for array initial function

In [2]:
import numpy as np
a=np.array([0,1,2,3,4])

### please be aware array only take 1 parameter as data input

In [3]:
a


array([0, 1, 2, 3, 4])

In [16]:
a.ndim

1

### 2-D Array

In [8]:
b = np.array(([0,1,2,3,4],[9,8,7,6,5]))

In [9]:
b


array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

### basic information about array

In [10]:
# 维度 Please be aware it's a var not a function
b.ndim

2

In [11]:
# 维度信息
b.shape

(2, 5)

In [12]:
# 多少个元素（所有维度）
b.size

10

### 3-D Dimention Array

In [63]:
c = np.array([[[1], [2]], [[3], [4]]])

In [73]:
cc = np.array([[[1],[3]],[[4],[7]]])

In [76]:
cc.ndim

3

In [75]:
c.shape

(2, 2, 1)

In [77]:
c.ndim

3

### Create Array from method()

In [78]:
d = np.arange(10)

In [79]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
dd = np.arange(0,9,2) # start, stop(exclusive, step

In [81]:
dd

array([0, 2, 4, 6, 8])

In [82]:
ddd = np.linspace(0,10, 6) # 线性等分向量 包括10

In [83]:
ddd

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [207]:
d4 = np.ones((3,3)) # 全是1的矩阵，注意参数是一个Tulip

In [208]:
d4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [209]:
d5 = np.zeros((4,4)) # All ZERO 2-D array

In [210]:
d5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [211]:
d6 = np.eye(4) # 单位矩阵

In [212]:
d6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [214]:
d6 = np.diag(np.arange(1,5)) # 奇怪的一种矩阵

In [215]:
d6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## use random function to generate DATA
## 使用随机数据生成相关的数据

In [218]:
e = np.random.rand(4) # rand returns (0-1)

In [219]:
e

array([0.51965296, 0.97640317, 0.41942749, 0.96327251])

In [220]:
ee = np.random.rand(4) # Gaussian 高斯正态分布

In [225]:
eee = np.random.randint(4,size=(3,3)) # 产生多维随机数组或矩阵

In [227]:
eee

array([[2, 1, 0],
       [3, 2, 3],
       [3, 0, 1]])

In [235]:
np.random.seed(123) # 随机种子设定

### Data Type

In [239]:
f = np.array([1,2,3,4])

In [242]:
f.dtype # var, not a function, don't connect ()

dtype('int64')

In [243]:
ff = np.array([1.0,2,3])

In [244]:
ff.dtype

dtype('float64')

In [246]:
fff = np.array([1,2,3,4], dtype=float) # 指定数据类型

In [247]:
fff.dtype

dtype('float64')

In [248]:
f3 = np.array([1j, 2j, 3j]) # complex 类型

In [249]:
f3

array([0.+1.j, 0.+2.j, 0.+3.j])

In [250]:
f3.dtype

dtype('complex128')