### create array for array initial function

In [3]:
import numpy as np
a=np.array([0,1,2,3,4])

### please be aware array only take 1 parameter as data input

In [4]:
a


array([0, 1, 2, 3, 4])

In [5]:
a.ndim

1

### 2-D Array

In [6]:
b = np.array(([0,1,2,3,4],[9,8,7,6,5]))

In [7]:
b


array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

### basic information about array

In [8]:
# 维度 Please be aware it's a var not a function
b.ndim

2

In [9]:
# 维度信息
b.shape

(2, 5)

In [10]:
# 多少个元素（所有维度）
b.size

10

### 3-D Dimention Array

In [11]:
c = np.array([[[1], [2]], [[3], [4]]])

In [12]:
cc = np.array([[[1],[3]],[[4],[7]]])

In [13]:
cc.ndim

3

In [14]:
c.shape

(2, 2, 1)

In [15]:
c.ndim

3

### Create Array from method()

In [16]:
d = np.arange(10)

In [17]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
dd = np.arange(0,9,2) # start, stop(exclusive, step

In [19]:
dd

array([0, 2, 4, 6, 8])

In [20]:
ddd = np.linspace(0,10, 6) # 线性等分向量 包括10

In [21]:
ddd

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
d4 = np.ones((3,3)) # 全是1的矩阵，注意参数是一个Tulip

In [23]:
d4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
d5 = np.zeros((4,4)) # All ZERO 2-D array

In [25]:
d5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
d6 = np.eye(4) # 单位矩阵

In [27]:
d6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
d6 = np.diag(np.arange(1,5)) # 奇怪的一种矩阵

In [29]:
d6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## use random function to generate DATA
## 使用随机数据生成相关的数据

In [30]:
e = np.random.rand(4) # rand returns (0-1)

In [31]:
e

array([0.4703944 , 0.94398304, 0.37036948, 0.65057309])

In [32]:
ee = np.random.rand(4) # Gaussian 高斯正态分布

In [33]:
eee = np.random.randint(4,size=(3,3)) # 产生多维随机数组或矩阵

In [34]:
eee

array([[1, 2, 3],
       [2, 1, 0],
       [2, 0, 1]])

In [35]:
np.random.seed(123) # 随机种子设定

### Data Type

In [36]:
f = np.array([1,2,3,4])

In [37]:
f.dtype # var, not a function, don't connect ()

dtype('int64')

In [38]:
ff = np.array([1.0,2,3])

In [39]:
ff.dtype

dtype('float64')

In [40]:
fff = np.array([1,2,3,4], dtype=float) # 指定数据类型

In [41]:
fff.dtype

dtype('float64')

In [42]:
f3 = np.array([1j, 2j, 3j]) # complex 类型

In [43]:
f3

array([0.+1.j, 0.+2.j, 0.+3.j])

In [44]:
f3.dtype

dtype('complex128')