### Array Indexing and Slicing

In [48]:
%matplotlib inline
import numpy as np

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[0],a[8],a[9] # 通过下标取元素

(0, 8, 9)

In [51]:
a[::-1] # -1 backward

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
a[6:8], a[9:7:-1] # 切片，相反方向

(array([6, 7]), array([9, 8]))

In [53]:
a[2:9:3] # [start: stop: step]

array([2, 5, 8])

In [54]:
a[:4] # start from beginning

array([0, 1, 2, 3])

In [55]:
a[::3]

array([0, 3, 6, 9])

In [56]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

### 多维数组或矩阵

In [57]:
aa = np.diag(np.arange(5)) #对角矩阵

In [58]:
aa

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [59]:
aa[1,1],aa[1][1],aa[2,2]

(1, 1, 2)

In [60]:
aa[2,1]=10

In [61]:
aa

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

In [62]:
aa[1] # get the data of the row 取行

array([0, 1, 0, 0, 0])

In [63]:
aa[1:3]

array([[ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0]])

In [64]:
aa[:,1] # get the data of colomn 取列

array([ 0,  1, 10,  0,  0])

In [65]:
aa

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

# valuation 赋值

In [66]:
aa[4:]=10
aa

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, 10,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [10, 10, 10, 10, 10]])

In [67]:
aa[4,4]=100

In [68]:
aa

array([[  0,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0],
       [  0,  10,   2,   0,   0],
       [  0,   0,   0,   3,   0],
       [ 10,  10,  10,  10, 100]])

In [69]:
aaa = np.arange(10)

In [70]:
aaa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
aaa[:,np.newaxis] #行变列

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Array+Array=Matrix,
#### Array1 has a row only, array2 has a column only
#### 用行和列数组生成矩阵

In [72]:
b=aaa[3:8,np.newaxis]
b

array([[3],
       [4],
       [5],
       [6],
       [7]])

In [73]:
bb=np.arange(5)
bb

array([0, 1, 2, 3, 4])

In [74]:
b+bb # array + array = matrix 

array([[ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [75]:
np.tile((3,6),3) # 重复一段数据 


array([3, 6, 3, 6, 3, 6])

## 作业 Exercise
#### 生成如下矩阵
##### [[1, 1, 1, 1],
#####  [1, 1, 1, 1],
#####  [1, 1, 1, 2],
#####  [1, 6, 1, 1]]
#####  
##### [[0., 0., 0., 0., 0.],
#####  [2., 0., 0., 0., 0.],
#####  [0., 3., 0., 0., 0.],
#####  [0., 0., 4., 0., 0.],
#####  [0., 0., 0., 5., 0.],
#####  [0., 0., 0., 0., 6.]]
#####  
#####  [[4, 3, 4, 3, 4, 3],
#####  [2, 1, 2, 1, 2, 1],
#####  [4, 3, 4, 3, 4, 3],
#####  [2, 1, 2, 1, 2, 1]]

In [76]:
ex1 = np.ones((4,4))
ex1[2,3]=2
ex1[3,1]=6

In [77]:
ex1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 2.],
       [1., 6., 1., 1.]])

### 多维数据可以通过flat转为一维 来迭代出每个元素

In [78]:
for x in ex1.flat:
    print (x)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
1.0
6.0
1.0
1.0


In [79]:
ex2 = np.zeros((6,5)) # 6 rows x 5 cols

In [80]:
for x in range(1,6):
    ex2[x][x-1]=x+1

In [81]:
ex2

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])

In [82]:
ex3 = np.array([np.tile((4,3),3),
                np.tile((2,1),3),
                np.tile((4,3),3),
                np.tile((2,1),3)])

In [83]:
ex3

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

### Copy and View
### 复制与视图
复制会生产一个一样的数据并占用不同的内存
视图还是引用的原数据，所以修改视图数据会改动原数据
可以用copy()函数强制复制数据
通常的slicing切片操作产生视图

In [84]:
a4 = np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
b4 = a4[::2]
b4

array([0, 2, 4, 6, 8])

In [86]:
np.may_share_memory(a4,b4)

True

In [87]:
b4[0]=11
b4

array([11,  2,  4,  6,  8])

In [88]:
a4

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [89]:
a4 = np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
c4 = a4[::2].copy()
c4

array([0, 2, 4, 6, 8])

In [91]:
np.may_share_memory(a4,c4)

False

In [92]:
c4[0]=11
c4

array([11,  2,  4,  6,  8])

In [93]:
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])