In [15]:
import numpy as np
np.random.seed(3)
a = np.random.randint(0,21,15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [16]:
(a%3==0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [17]:
mask = (a %3 ==0)

In [18]:
extract_from_array = a[mask] # or = a[a%3==0]
extract_from_array

array([ 3,  0,  9,  6,  0, 12])

In [19]:
np.may_share_memory(extract_from_array,a) # 不共享内存

False

In [20]:
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [21]:
a[a%3==0]=-1

In [22]:
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

### using list as indexing 
### 使用Python的list作为数据的索引和下标

In [23]:
aa = np.arange(0,100,10)
aa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
aa[[2,3,2,4,2]] # [] is python list 

array([20, 30, 20, 40, 20])

In [25]:
aa[[9,7]] = -1  #注意不是切片，是列表作为下标
aa

array([ 0, 10, 20, 30, 40, 50, 60, -1, 80, -1])

In [26]:
idx = np.array([[1,2],[3,4]]) # 2-D 的下标会使产生的结果也是2D
aa[idx]

array([[10, 20],
       [30, 40]])

In [30]:
a3 = np.arange(0,60,10)[:,np.newaxis]+np.arange(0,6) # 

In [31]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [32]:
a3[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [33]:
a3[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [38]:
mask_a3 = np.array([1,0,1,0,1,1], dtype=bool) # 1代表需要的行
a3[mask_a3,1] # True行，和下标为2的值

array([ 1, 21, 41, 51])

## Exercise 将a3 array中能被5整除的值设为-1

In [39]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [40]:
a_mask = a3%5==0

In [41]:
a_mask

array([[ True, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [ True, False, False, False, False,  True]])

In [42]:
a3[a_mask]=-1

In [43]:
a3

array([[-1,  1,  2,  3,  4, -1],
       [-1, 11, 12, 13, 14, -1],
       [-1, 21, 22, 23, 24, -1],
       [-1, 31, 32, 33, 34, -1],
       [-1, 41, 42, 43, 44, -1],
       [-1, 51, 52, 53, 54, -1]])