## elementwise operations 
### 元素对元素的运算

In [6]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a+1

array([2, 3, 4, 5])

In [5]:
2**a

array([ 2,  4,  8, 16])

### 元素对元素的四则运算 + - * /
### All arithmetic operates elementwise

In [15]:
b = np.ones(4)+1

In [16]:
b

array([2., 2., 2., 2.])

In [17]:
a-b

array([-1.,  0.,  1.,  2.])

In [18]:
a*b

array([2., 4., 6., 8.])

### numpy 的运算速大大快过python list的运算速度

In [21]:
aa= np.arange(10000)
%timeit aa+1

5.1 µs ± 34.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
aaa = range(10000)
%timeit [i+1 for i in aaa]

794 µs ± 4.25 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 2-D 数组的乘法 不等于  矩阵乘法

In [24]:
c = np.ones((3,3))
c*c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# matrix dot 矩阵点乘
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### Exercise 将一个array的奇数位和偶数位相加

In [40]:
ex1 = np.arange(100)
mask_even = np.array(np.tile((1,0),50),dtype=bool)

In [41]:
mask_odd = np.array(np.tile((0,1),50),dtype=bool)

In [42]:
ex_result = ex1[mask_even]+ex1[mask_odd]

In [43]:
len(ex_result)

50

In [45]:
ex1,ex_result

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
         53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
        105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
        157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197]))

### 比较 Comparisons

In [56]:
a3 = np.array([1,2,3,4])
b3 = np.array([4,2,2,4])

In [57]:
a3==b3

array([False,  True, False,  True])

In [58]:
a3>b3

array([False, False,  True, False])

In [59]:
c3 = np.array([1,2,3,4])

In [60]:
a3==c3

array([ True,  True,  True,  True])

In [61]:
np.array_equal(a3,c3) # 数组比较 （非元素对元素比较）

True

In [62]:
np.array_equal(a3,b3) # Array-wise comparasion

False

In [63]:
a4 = np.array([1,1,0,0])
b4 = np.array([1,0,1,0])
a4 & b4

array([1, 0, 0, 0])

In [67]:
np.logical_and(a4,b4)

array([ True, False, False, False])

In [66]:
np.logical_or(a4,b4)  

array([ True,  True,  True, False])

In [68]:
np.logical_not(a4)

array([False, False,  True,  True])

### Transcendental 超越数 函数
### sin() log() exp() ...

In [69]:
a5 = np.arange(5)

In [70]:
np.sin(a5)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [71]:
np.log(a5)

/Users/eddy/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [73]:
np.exp(a5)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])