## elementwise operations 
### 元素对元素的运算

In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
a+1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16])

### 元素对元素的四则运算 + - * /
### All arithmetic operates elementwise

In [4]:
b = np.ones(4)+1

In [5]:
b

array([2., 2., 2., 2.])

In [6]:
a-b

array([-1.,  0.,  1.,  2.])

In [7]:
a*b

array([2., 4., 6., 8.])

### numpy 的运算速大大快过python list的运算速度

In [8]:
aa= np.arange(10000)
%timeit aa+1

5 µs ± 65.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
aaa = range(10000)
%timeit [i+1 for i in aaa]

832 µs ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 2-D 数组的乘法 不等于  矩阵乘法

In [10]:
c = np.ones((3,3))
c*c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# matrix dot 矩阵点乘
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### Exercise 将一个array的奇数位和偶数位相加

In [12]:
ex1 = np.arange(100)
mask_even = np.array(np.tile((1,0),50),dtype=bool)

In [13]:
mask_odd = np.array(np.tile((0,1),50),dtype=bool)

In [14]:
ex_result = ex1[mask_even]+ex1[mask_odd]

In [15]:
len(ex_result)

50

In [16]:
ex1,ex_result

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
         53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
        105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
        157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197]))

### 比较 Comparisons

In [17]:
a3 = np.array([1,2,3,4])
b3 = np.array([4,2,2,4])

In [18]:
a3==b3

array([False,  True, False,  True])

In [19]:
a3>b3

array([False, False,  True, False])

In [20]:
c3 = np.array([1,2,3,4])

In [21]:
a3==c3

array([ True,  True,  True,  True])

In [22]:
np.array_equal(a3,c3) # 数组比较 （非元素对元素比较）

True

In [23]:
np.array_equal(a3,b3) # Array-wise comparasion

False

In [24]:
a4 = np.array([1,1,0,0])
b4 = np.array([1,0,1,0])
a4 & b4

array([1, 0, 0, 0])

In [25]:
np.logical_and(a4,b4)

array([ True, False, False, False])

In [26]:
np.logical_or(a4,b4)  

array([ True,  True,  True, False])

In [27]:
np.logical_not(a4)

array([False, False,  True,  True])

### Transcendental 超越数 函数
### sin() log() exp() ...

In [28]:
a5 = np.arange(5)

In [29]:
np.sin(a5)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.log(a5)

/Users/eddy/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(a5)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### 基本运算


In [32]:
a6 = np.arange(6)

In [33]:
a6

array([0, 1, 2, 3, 4, 5])

In [34]:
%timeit sum(a6)

1.35 µs ± 28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
%timeit np.sum(a6)

3.22 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
%timeit a6.sum()

2.09 µs ± 20.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 7 axis 的概念在多维数组和矩阵中的应用 

In [37]:
a7 = np.array([[1,2],[3,4]])
a7

array([[1, 2],
       [3, 4]])

In [38]:
a7.sum(axis=0) # axis = 0 取每列的和

array([4, 6])

In [39]:
a7[:,0].sum(),a7[:,1].sum() # 同上，取每列的和

(4, 6)

In [40]:
a7.sum(axis=1) # axis =1 , 取行的和

array([3, 7])

In [41]:
a7[0,:].sum(), a7[1,:].sum() #  取行的和

(3, 7)

## 8 取最大最小值，以及快速找出最大最小值的下标(Index)

In [42]:
a8 = np.random.randint(10,size=10)

In [43]:
a8

array([3, 1, 7, 3, 6, 7, 9, 0, 9, 4])

In [44]:
a8.min(),a8.max()

(0, 9)

In [45]:
a8.argmin(), a8.argmax() # index of minimal number and maxiam number

(7, 6)

### 9 逻辑运算

In [46]:
a9 = np.random.randint(2, size=3,dtype=bool) # 0 ak 1

In [47]:
a9

array([False, False, False])

In [48]:
np.all(a9)

False

In [49]:
np.any(a9)

False

## 10 Statistics 统计算法

In [50]:
a10 = np.random.randint(100,size=10)

In [51]:
a10

array([24, 56, 19, 64, 64, 43, 83, 34, 41, 19])

In [52]:
a10.mean() # 均值函数

44.7

In [53]:
np.median(a10) # 中位数函数


42.0

In [54]:
a10.std() # 矩阵或数据的标准差

20.54288197892399

In [55]:
a11 = np.arange(10)
a11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a11.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])