In [1]:
import numpy as np

### 1-多维数据或矩阵的形状改变

In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a.ravel() ## 以一维方式输出所有元素 生成的顺序是C-Style 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
[print(x) for x in a.flat] #注意flat是常量，不是函数

0
1
2
3
4
5
6
7
8
9
10
11


[None, None, None, None, None, None, None, None, None, None, None, None]

### reshape()返回一个新的数组，而ndarray.resize()改变数组本身 

In [13]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a.resize(4,3)

In [16]:
a # 改变了

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 2-数组的堆叠

In [17]:
aa = np.arange(4).reshape(2,2)

In [18]:
aa

array([[0, 1],
       [2, 3]])

In [19]:
bb = np.arange(4).reshape([2,2])

In [20]:
bb

array([[0, 1],
       [2, 3]])

In [27]:
cv=np.vstack((aa,bb))
cv

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [29]:
ch = np.hstack((aa,bb))
ch

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

#### 分割操作  np.hsplit and np.vsplit

In [31]:
c1,c2=np.hsplit(ch,2) # 2是分割的数量，分成2个

In [32]:
c1 

array([[0, 1],
       [2, 3]])

In [33]:
c2

array([[0, 1],
       [2, 3]])