In [35]:
import numpy as np

### 1-多维数据或矩阵的形状改变

In [36]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a.ravel() ## 以一维方式输出所有元素 生成的顺序是C-Style 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
[print(x) for x in a.flat] #注意flat是常量，不是函数

0
1
2
3
4
5
6
7
8
9
10
11


[None, None, None, None, None, None, None, None, None, None, None, None]

### reshape()返回一个新的数组，而ndarray.resize()改变数组本身 

In [39]:
a.reshape(4,3) # 返回一个新的数组，自身不变

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a.resize(4,3)

In [42]:
a # 改变了自身

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 2-数组的堆叠

In [43]:
aa = np.arange(4).reshape(2,2)

In [44]:
aa

array([[0, 1],
       [2, 3]])

In [45]:
bb = np.arange(4).reshape([2,2])

In [46]:
bb

array([[0, 1],
       [2, 3]])

In [47]:
c_v=np.vstack((aa,bb))
c_v

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [48]:
c_h = np.hstack((aa,bb))
c_h

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

#### 分割操作  np.hsplit and np.vsplit

In [49]:
c1,c2=np.hsplit(ch,2) # 2是分割的数量，分成2个

In [50]:
c1 

array([[0, 1],
       [2, 3]])

In [51]:
c2

array([[0, 1],
       [2, 3]])